version: 2
updates:
- package-ecosystem: pip
  directory: "dev_requirements/"
  schedule:
    interval: daily
    time: "09:00"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
